name: excell_employee
description: Excell Employee Project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  local_auth: ^1.1.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.4
  date_format: ^2.0.2
  http: ^0.13.0
  firebase_core: ^1.0.1
  firebase_analytics: ^7.1.1
  cloud_firestore: ^1.0.1
  firebase_database: ^6.1.0
  smart_select: ^4.3.2
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Lato
  #     fonts:
  #       - asset: assets/fonts/Lato-Regular.ttf
  #       - asset: assets/fonts/Lato-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
